const quotes = [
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Eighty percent of success is showing up.", author: "Woody Allen" },
    { text: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "Winning isn’t everything, but wanting to win is.", author: "Vince Lombardi" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
    { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
    { text: "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
    { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
    { text: "Whether you think you can, or you think you can’t, you’re right.", author: "Henry Ford" },
    { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
    { text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily.", author: "Zig Ziglar" },
    { text: "Life shrinks or expands in proportion to one’s courage.", author: "Anais Nin" },
    { text: "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.", author: "Vincent Van Gogh" },
    { text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle" },
    { text: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { text: "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", author: "Erma Bombeck" },
    { text: "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", author: "Booker T. Washington" },
    { text: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb" },
    { text: "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.", author: "Norman Vincent Peale" },
    { text: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "Don’t judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Your happiness is determined by how you allocate your attention.", author: "Tim Ferriss" },
    { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
    { text: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.", author: "Jordan Belfort" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { text: "You become what you believe.", author: "Oprah Winfrey" },
    { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
    { text: "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", author: "Ann Landers" },
    { text: "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.", author: "Sheryl Sandberg" },
    { text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
    { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.", author: "Unknown" },
    { text: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", author: "Marie Curie" },
    { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
    { text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", author: "Leonardo da Vinci" },
    { text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
    { text: "You take your life in your own hands, and what happens? A terrible thing, no one to blame.", author: "Erica Jong" },
    { text: "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan" },
    { text: "I didn’t fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
    { text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The person who reads too much and uses his brain too little will fall into lazy habits of thinking.", author: "Albert Einstein" },
    { text: "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.", author: "Jim Rohn" },
    { text: "The question isn’t who is going to let me; it’s who is going to stop me.", author: "Ayn Rand" },
    { text: "The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle.", author: "Steve Jobs" },
    { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
    { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
    { text: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "I have learned over the years that when one’s mind is made up, this diminishes fear.", author: "Rosa Parks" },
    { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
    { text: "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", author: "Ann Landers" },
    { text: "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.", author: "Sheryl Sandberg" },
    { text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
    { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.", author: "Unknown" },
    { text: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", author: "Marie Curie" },
    { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
    { text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", author: "Leonardo da Vinci" },
    { text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
    { text: "You take your life in your own hands, and what happens? A terrible thing, no one to blame.", author: "Erica Jong" },
    { text: "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan" },
    { text: "I didn’t fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
    { text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The person who reads too much and uses his brain too little will fall into lazy habits of thinking.", author: "Albert Einstein" },
    { text: "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.", author: "Jim Rohn" },
    { text: "The question isn’t who is going to let me; it’s who is going to stop me.", author: "Ayn Rand" },
    { text: "The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle.", author: "Steve Jobs" },
    { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
    { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
    { text: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "I have learned over the years that when one’s mind is made up, this diminishes fear.", author: "Rosa Parks" },
  ];
  
  const quoteElement = document.getElementById("quote");
  const authorElement = document.getElementById("author");
  const generateBtn = document.getElementById("generate-btn");
  
  function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
  }
  
  function displayQuote() {
    const { text, author } = getRandomQuote();
    quoteElement.textContent = text;
    authorElement.textContent = `— ${author}`;
  }
  
  generateBtn.addEventListener("click", displayQuote);
  
  // Display a quote on page load
  displayQuote();